const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// Generate PDF meeting minutes
function generateMeetingPDF(meeting, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50
      });

      const stream = fs.createWriteStream(outputPath);
      doc.pipe(stream);

      // Header
      doc.fontSize(24).font('Helvetica-Bold').text('Meeting Minutes', { underline: true });
      doc.moveDown(0.5);

      // Meeting Info
      doc.fontSize(11).font('Helvetica');
      doc.text(`Title: ${meeting.title}`, { underline: true });
      doc.text(`Date: ${new Date(meeting.createdAt).toLocaleString()}`);
      doc.text(`Updated: ${new Date(meeting.updatedAt).toLocaleString()}`);
      
      if (meeting.attendees && meeting.attendees.length > 0) {
        doc.text(`Attendees: ${meeting.attendees.join(', ')}`);
      }

      if (meeting.description) {
        doc.text(`Description: ${meeting.description}`);
      }

      doc.moveDown(1);

      // Summary Section
      if (meeting.summary) {
        doc.fontSize(14).font('Helvetica-Bold').text('📋 Summary', { underline: true });
        doc.fontSize(11).font('Helvetica').text(meeting.summary);
        doc.moveDown(0.8);
      }

      // Key Points Section
      if (meeting.keyPoints && meeting.keyPoints.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').text('🎯 Key Points', { underline: true });
        doc.fontSize(11).font('Helvetica');
        meeting.keyPoints.forEach((point, idx) => {
          doc.text(`${idx + 1}. ${point}`);
        });
        doc.moveDown(0.8);
      }

      // Key Decisions Section
      if (meeting.decisions && meeting.decisions.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').text('✓ Key Decisions', { underline: true });
        doc.fontSize(11).font('Helvetica');
        meeting.decisions.forEach((decision, idx) => {
          doc.text(`${idx + 1}. ${decision}`);
        });
        doc.moveDown(0.8);
      }

      // Action Items / Tasks Section
      if (meeting.tasks && meeting.tasks.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').text('📌 Action Items', { underline: true });
        doc.fontSize(10).font('Helvetica');
        
        meeting.tasks.forEach((task, idx) => {
          const status = task.status === 'completed' ? '✓' : '○';
          doc.text(`${status} [${task.priority.toUpperCase()}] ${task.title}`);
          doc.text(`   Assigned to: ${task.assignee}`, { indent: 10 });
          if (task.dueDate) {
            doc.text(`   Due: ${new Date(task.dueDate).toLocaleDateString()}`, { indent: 10 });
          }
          doc.text(`   Status: ${task.status}`, { indent: 10 });
        });
        doc.moveDown(0.8);
      }

      // Original Transcript Section
      if (meeting.transcript) {
        doc.addPage();
        doc.fontSize(14).font('Helvetica-Bold').text('📝 Original Transcript', { underline: true });
        doc.fontSize(9).font('Helvetica').text(meeting.transcript, {
          align: 'left',
          wrapping: true
        });
      }

      // Footer
      doc.moveDown(1);
      doc.fontSize(8).font('Helvetica').fillColor('gray').text(
        `Generated by Meeting Minder on ${new Date().toLocaleString()}`,
        { align: 'center' }
      );

      doc.end();

      stream.on('finish', () => {
        console.log('PDF generated successfully:', outputPath);
        resolve(outputPath);
      });

      stream.on('error', (err) => {
        reject(new Error(`Stream error: ${err.message}`));
      });
    } catch (error) {
      reject(new Error(`PDF generation error: ${error.message}`));
    }
  });
}

module.exports = {
  generateMeetingPDF
};
